apiVersion: v2
kind: Pod
metadata:
  name: multi-pod-pass
spec:
  containers:
  - name: nginx-container-1
    image: nginx
    ports:
    - containerPort: 80
  containers:
     name: nginx-container-2
     image: ubuntu
     ports:
       containerPort: 81